# @package _global_
defaults:
  - override /data: mocap/trainX_testY
  - override /model: gvhmr/gvhmr_pl
  - override /endecoder: gvhmr/v1_amass_local_bedlam_cam_clipstd
  - override /optimizer: adamw_2e-4
  - override /scheduler_cfg: epoch_half_200_350
  - override /train_datasets:
      - pure_motion_amass/v11
      - imgfeat_bedlam/v2
      - imgfeat_h36m/v1
      - imgfeat_3dpw/v1
  - override /test_datasets:
      - emdb1/v1_fliptest
      - emdb2/v1_fliptest
      - rich/all
      - 3dpw/fliptest
  - override /callbacks:
      - simple_ckpt_saver/every10e_top100
      - prog_bar/prog_reporter_every0.1
      - train_speed_timer/base
      - lr_monitor/pl
      - metric_emdb1
      - metric_emdb2
      - metric_rich
      - metric_3dpw

exp_name_base: mixed_2step_ddim_rope_new
exp_name_var: ""
exp_name: ${exp_name_base}_${exp_name_var}
data_name: mocap_mixed_v1

pipeline:
  _target_: hmr4d.model.gvhmr.pipeline.mfm_pipeline2.Pipeline
  args_denoiser3d:
    _target_: hmr4d.network.mdm.mdm_2step_rope3.MDM2Step
    args: ${pipeline.args}
    model_cfg:
      # pretrained_checkpoint:
      #     path:  /lustre/fsw/portfolios/nvr/projects/nvr_torontoai_humanmotionfm/workspaces/motiondiff/motiondiff_results/jiefengl/jiefengl/mdm_egosmpl_v12_contact_b64_gpu8_node1/version_3/checkpoints/model-step=0100000.ckpt
      #     strict: false
      #     try_load: true
      diffusion:
        sampler: ddim
        train_timestep_respacing: ""
        test_timestep_respacing: "5"
        schedule_sampler_type: uniform
        noise_schedule: cosine
        sigma_small: true
        guidance_param: 2.5
        ddim_eta: 0.0
      denoiser:
        type: hmr4d.network.mdm.mdm_denoiser_rope2.MDMDenoiserROPE
        modeltype: ""
        nfeats: 1
        num_actions: 1
        num_frames: ${pipeline.args_denoiser3d.max_len}
        njoints: ${pipeline.args_denoiser3d.motion_rep_dim}
        output_dim: ${pipeline.args_denoiser3d.motion_rep_dim}
        translation: true
        pose_rep: rot6d
        # hint_rep: kpt2d_cam_vel
        glob: true
        glob_rot: true
        latent_dim: 512
        ff_size: 512
        num_layers: 8
        num_heads: 8
        dropout: 0.1
        activation: gelu
        data_rep: hml_vec
        cond_mode: text
        # cond_mode: text,kpt2d_cam_vel
        cond_mask_prob: 0.5
        # cond_mask_prob: 0.5
        # cond_kptcammask_prob: 0.5
        # cond_camvelmask_prob: 0.5
        action_emb: tensor
        arch: trans_enc
        emb_trans_dec: false
        max_text_len: 50
        text_embed_model: t5
        llm_dim: 1024
        llm_version: "t5-3b"
        text_enc_mode: seq_concat
        # control_layers:
        #     l3: l3
        #     l4: l3
        #     l5: l3
        #     l6: l3
        #     l7: l3
        use_motion_mask: true
        args: ${pipeline.args}

    motion_rep_dim: 157
    max_len: 120
    cliffcam_dim: 3
    cam_angvel_dim: 6
    cam_t_vel_dim: 3
    imgseq_dim: 1024
    latent_dim: 512
    num_layers: 12
    num_heads: 8
    mlp_ratio: 4.0
    pred_cam_dim: 3
    static_conf_dim: 6
    preload_checkpoint: true

  args:
    endecoder_opt: ${endecoder}
    normalize_cam_angvel: True
    weights:
      cr_j3d: 500.
      transl_c: 1.
      cr_verts: 500.
      j2d: 1000.
      verts2d: 1000.

      transl_w: 1.
      static_conf_bce: 1.

    static_conf:
      vel_thr: 0.15

    infer_version: 2
    in_attr:
      - obs
      - bbx
      - imgfeat
      - cam_angvel
      # - cam_t_vel
    uncond_prob:
      obs: 0.1
      f_cliffcam: 0.1
      f_imgseq: 0.5
      f_cam_angvel: 0.5
      # f_cam_t_vel: 0.1
    out_attr:
      pred_cam: 3
      # cam_t_vel: 3
      # - cam_angvel
      # - cam_scale

data:
  loader_opts:
    train:
      batch_size: 256
      num_workers: 12

pl_trainer:
  precision: 16-mixed
  log_every_n_steps: 10
  gradient_clip_val: 0.5
  max_epochs: 500
  check_val_every_n_epoch: 10
  devices: 1

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: "mfm-hmr"
  entity: "nvr-lpr"
  save_dir: "/tmp" # /save_dir/name/version/sub_dir
  name: ""
  version: ""
  resume: "allow"
  dir: "/tmp"
  id: null
