# TODO: should change the runner to be a proper docker container
#       if we want to run anything more sophisticated (unit tests).
#       Right now it's just ssh-ing into a horde instance with fixed env.
#       See the process here: https://confluence.nvidia.com/pages/viewpage.action?pageId=2565826909
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages: # List of stages for jobs, and their order of execution
  - format

format:
  stage: format
  script:
    - pre-commit run --all-files
