# @package _global_
# based on unimfm_est_wtext_grep_reg_new3_j2d2_st_norm
defaults:
  - /diffusion@model_cfg.diffusion: ddim
  - /phc: config_kitchen_v1
  - /phc/data_gen: kitchen_v1
  - override /data: mocap/trainX_testY
  - override /model: gvhmr/unimfm
  - override /endecoder: gvhmr/humanoid_z_action
  - override /optimizer: adamw_1e-4
  - override /scheduler_cfg: epoch_half_200_350
  - override /train_datasets:
      - phc/v1
      # - pure_motion_humanml3d/humanoid_train_im_v1
      # - pure_motion_humanml3d/humanoid_train_im_v1
      # - imgfeat_bedlam/v2
      # - imgfeat_h36m/v1
      # - imgfeat_3dpw/v1
      # - imgfeat_3dpw_occ/v1
  # - override /train_2d_datasets:
  #     - bones_2d
  - override /test_datasets:
      - humanml3d_eval_humanoid
      # - imgfeat_motionx/v2d_test32
      # - emdb1/v1_fliptest
      # - emdb2/v1_fliptest
      # - rich/all
      # - 3dpw/fliptest
      # - 3dpw_occ/fliptest
      #   - bones_2d_test
  - override /callbacks:
      - simple_ckpt_saver/every10000s_top100
      - prog_bar/prog_reporter_every0.1
      - train_speed_timer/base
      - lr_monitor/pl
      - phc_data_collect
      # - vis_text
      # - metric_emdb1
      # - metric_emdb2
      # - metric_rich
      # - metric_3dpw
      # - metric_3dpw_occ
  - _self_

phc:
  env:
    num_envs: 512

callbacks:
  phc_data_collect:
    every_n_epochs: 4
    collect_kwargs:
      num_episodes: 200

exp_name_base: ${hydra:runtime.choices.exp}
exp_name_var: ""
exp_name: ${exp_name_base}_${exp_name_var}
data_name: mocap_mixed_v1
# pretrain_2d_ckpt: "/lustre/fsw/portfolios/nvr/projects/nvr_torontoai_humanmotionfm/workspaces/motiondiff/motiondiff_results/yey/gvhmr/mocap_mixed_v1/mv2d/diff2d/diff2d_base_tt/version_0/checkpoints/last.ckpt"

model_cfg:
  train_3d_modes: ["regression"]
  train_2d_modes: []
  start_2d_training_steps: 0
  noisy_2d_obs: true
  kp2d_noise_scale: 0.5
  perframe_condition_exists: true

  diffusion:
    test_timestep_respacing: "50"
    guidance_param: 2.5

  text_encoder:
    load_llm: false
    llm_version: "t5-3b"
    max_text_len: 50

  mask_cfg:
    drop_prob: 0.75
    max_num_drops: 3
    min_drop_nframes: 1
    max_drop_nframes: 30
  body_mask_cfg:
    drop_prob: 0.75
    joint_drop_prob: 0.25
    max_num_drops: 3
    min_drop_nframes: 1
    max_drop_nframes: 30

pipeline:
  _target_: hmr4d.model.gvhmr.pipeline.unimfm_pipeline.Pipeline
  args_denoiser3d: ${network}
  args:
    endecoder_opt: ${endecoder}
    humanoid_obs_dim: 778
    normalize_cam_angvel: true
    use_regression_outputs_prob: 0.
    use_cfg_sampler_for_text: true
    inpaint_x_start_gt: false
    regression_only: false
    humanoid_use_rgb_raw: true
    humanoid_use_text: true
    weights:
      simple: 0.
      cr_j3d: 0.
      transl_c: 0.
      cr_verts: 0.
      j2d: 0.
      verts2d: 0.

      j2d_train2d: 0.
      # norm_j2d: 1000.
      train2d_skip_regression: false

      transl_w: 0.
      static_conf_bce: 0.

      humanoid_z_action: 1.

    static_conf:
      vel_thr: 0.15

    in_attr:
      # - obs
      # - f_cliffcam
      # - f_imgseq
      # - f_cam_angvel
      - humanoid_obs
      - humanoid_contact_force
      - humanoid_rgb_obs
    humanoid_rgb_obs_dim: [3, 128, 128]
    norm_attr_stats:
      humanoid_obs: "inputs/humanoid/running_stats/dais_rgbd_0223/humanoid_obs_stats.p"
      humanoid_contact_force: "inputs/humanoid/running_stats/dais_rgbd_0223/humanoid_contact_force_stats.p"
    mask_out_attr: [] # ${.in_attr}
    out_attr: {}

network:
  _target_: hmr4d.network.unimfm.unimfm_diffusion.UNIMFMDiffusion
  args: ${pipeline.args}
  latent_dim: ${.model_cfg.denoiser.latent_dim}
  humanoid_obs_dim: ${pipeline.args.humanoid_obs_dim}
  use_cond_exists_as_input: true
  cond_merge_strategy: "add"
  img_process_modules:
    humanoid_rgb_obs:
      _target_: hmr4d.network.base_arch.vision.vit.VITEncoder
      input_dim: ${pipeline.args.humanoid_rgb_obs_dim}
      latent_dim: ${network.model_cfg.denoiser.latent_dim}
  img_process_modules_enable_grad:
    humanoid_rgb_obs: false
  model_cfg:
    diffusion: ${model_cfg.diffusion}
    denoiser:
      _target_: hmr4d.network.unimfm.unimfm_denoiser.NetworkEncoderRoPE
      output_dim: 48
      xt_dim: ${.output_dim}
      njoints: ${.xt_dim}
      text_mask_prob: 0.0
      use_text_pos_enc: true
      text_encoder_cfg:
        mode: all
        cross_attn_type: mha
      latent_dim: 512
      num_layers: 8
      num_heads: 8
      mlp_ratio: 4
      avgbeta: false

data:
  loader_opts:
    train:
      batch_size: 32
      num_workers: 6
    train_2d:
      batch_size: 16
      num_workers: 6
  # train_2d_only: true

pl_trainer:
  precision: 16-mixed
  log_every_n_steps: 10
  gradient_clip_val: 0.5
  max_epochs: null
  check_val_every_n_epoch: null
  val_check_interval: 30000000000000
  max_steps: 200000
  devices: 1
  strategy: ddp_find_unused_parameters_true

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: "mfm-hmr"
  entity: "nvr-lpr"
  save_dir: "/tmp" # /save_dir/name/version/sub_dir
  name: ""
  version: ""
  resume: "allow"
  dir: "/tmp"
  id: null
