# @package _global_
# based on genmo_lg
defaults:
  - /diffusion@model_cfg.diffusion: ddim
  - override /data: mocap/trainX_testY
  - override /model: genmo/genmo
  - override /endecoder: gvhmr/v1_amass_local_bedlam_cam
  - override /optimizer: adamw_2e-4
  - override /scheduler_cfg: epoch_half_200_350
  - override /train_datasets:
      - pure_motion_amass/v11
      - pure_motion_humanml3d/static_train
      - imgfeat_bedlam/v2
      - imgfeat_h36m/v1
      - imgfeat_3dpw/v1
      - imgfeat_3dpw_occ/v1
      - aistpp_train
      - beat2_static_train
  # - override /train_2d_datasets:
  #     - bones_2d
  - override /test_datasets:
      # - aistpp_test
      - humanml3d_eval
      # - imgfeat_motionx/v2d_test32
      - emdb1/v1_fliptest
      - emdb2/v1_fliptest
      - rich/all
      - 3dpw/fliptest
      - 3dpw_occ/fliptest
      #   - bones_2d_test
  - override /callbacks:
      - simple_ckpt_saver/every10000s_top100
      - prog_bar/prog_reporter_every0.1
      - train_speed_timer/base
      - lr_monitor/pl
      - vis_text
      - metric_emdb1
      - metric_emdb2
      - metric_rich
      - metric_3dpw
      - metric_3dpw_occ
      # - metric_aistpp
  - _self_
exp_name_base: ${hydra:runtime.choices.exp}
exp_name_var: ""
exp_name: ${exp_name_base}_${exp_name_var}
data_name: mocap_mixed_v1
# pretrain_2d_ckpt: "/lustre/fsw/portfolios/nvr/projects/nvr_torontoai_humanmotionfm/workspaces/motiondiff/motiondiff_results/yey/gvhmr/mocap_mixed_v1/mv2d/diff2d/diff2d_base_tt/version_0/checkpoints/last.ckpt"

train_datasets:
  aistpp_train:
    feat_version: v2
# test_datasets:
#   aistpp_test:
#       feat_version: v2

multicond_args: null

model_cfg:
  train_modes: ["regression", "diffusion"]
  noisy_2d_obs: true
  kp2d_noise_scale: 0.5
  perframe_condition_exists: true
  train2d_mask_invis_obs: true
  mask_occluded_imgfeats: true
  cond_merge_strategy: "add"
  use_cond_exists_as_input: true
  normalize_cam_angvel: true

  diffusion:
    test_timestep_respacing: "50"
    guidance_param: 2.5

  text_encoder:
    load_llm: false
    llm_version: "t5-3b"
    max_text_len: 50

  condition_mask:
    mask_img_prob: 0.5
    mask_cam_prob: 1.0
    reuse_regression_mask: false
    regression_no_img_mask: true

  mask_cfg:
    drop_prob: 0.75
    max_num_drops: 3
    min_drop_nframes: 1
    max_drop_nframes: 30
  body_mask_cfg:
    drop_prob: 0.75
    joint_drop_prob: 0.25
    max_num_drops: 3
    min_drop_nframes: 1
    max_drop_nframes: 30
  music_mask_prob: 0.1
  audio_mask_prob: 0.1

pipeline:
  _target_: hmr4d.model.genmo.genmo_pipeline.Pipeline
  args_denoiser3d: ${network}
  args:
    endecoder_opt: ${endecoder}
    use_regression_outputs_prob: 0.
    use_cfg_sampler_for_gen: true
    inpaint_x_start_gt: false
    regression_only: true
    encoded_music_dim: 35
    multicond_args: ${multicond_args}
    weights:
      cr_j3d: 500.
      transl_c: 1.
      cr_verts: 500.
      j2d: 1000.
      j2d_17: 1000.
      verts2d: 1000.

      proj_gt_j2d_to_bi01: true

      transl_w: 1.
      static_conf_bce: 1.

    static_conf:
      vel_thr: 0.15

    in_attr:
      - obs
      - f_cliffcam
      - f_imgseq
      - f_cam_angvel
      - encoded_music
      - encoded_audio
    mask_out_attr: [] # ${.in_attr}
    out_attr:
      pred_cam: 3

network:
  _target_: hmr4d.network.genmo.genmo_diffusion.GENMODiffusion
  args: ${pipeline.args}
  latent_dim: ${.model_cfg.denoiser.latent_dim}
  cond_merge_strategy: "add"
  music_mask_prob: ${.model_cfg.denoiser.music_mask_prob}
  speech_mask_prob: ${.model_cfg.denoiser.speech_mask_prob}
  encoded_music_dim: ${pipeline.args.encoded_music_dim}
  model_cfg:
    diffusion: ${model_cfg.diffusion}
    denoiser:
      _target_: hmr4d.network.genmo.genmo_denoiser.NetworkEncoderRoPE
      output_dim: 151
      xt_dim: ${.output_dim}
      njoints: ${.xt_dim}
      text_mask_prob: 0.1
      music_mask_prob: 0.1
      speech_mask_prob: 0.1
      use_text_pos_enc: true
      text_encoder_cfg:
        mode: all
        cross_attn_type: mha
      latent_dim: 1024
      num_layers: 16
      num_heads: 8
      mlp_ratio: 4

data:
  loader_opts:
    train:
      batch_size: 128
      num_workers: 6
    encoded_music_dim: ${pipeline.args.encoded_music_dim}
  # train_2d_only: true

pl_trainer:
  precision: 16-mixed
  log_every_n_steps: 10
  gradient_clip_val: 0.5
  max_epochs: null
  check_val_every_n_epoch: null
  val_check_interval: 3000
  max_steps: 200000
  devices: 1
  strategy: ddp_find_unused_parameters_true

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: "mfm-hmr"
  entity: "nvr-lpr"
  save_dir: "/tmp" # /save_dir/name/version/sub_dir
  name: ""
  version: ""
  resume: "allow"
  dir: "/tmp"
  id: null

no_wandb: false
