defaults:
  # pytorch-lightning
  - data: ???
  - model: ???
  - /text_encoder@model.model_cfg.text_encoder: t5_3b
  - callbacks: null

  # system
  - hydra: default

  # utility groups that changes a lot
  - pipeline: null
  - network: null
  - optimizer: null
  - scheduler: null
  - train_datasets: null
  - test_datasets: null
  - endecoder: null # normalize/unnormalize data
  - refiner: null

  # global-override
  - exp: mixed # set "data, model and callbacks" in yaml
  - global/task: null # dump/test
  - global/hsearch: null # hyper-param search
  - global/debug: null # debug mode
  - _self_

# ================================ #
#          global setting          #
# ================================ #


# expirement information
task: fit # [fit, predict]
exp_name_base: ???
exp_name_var: ""
exp_name: ${exp_name_base}_${exp_name_var}
data_name: ???

# utilities in the entry file
# output_dir: "outputs/${data_name}/${exp_name}"
resume_mode: null
seed: 42

version: null
ckpt_dir: outputs/${data_name}/${exp_name}/
remote_results_path: /lustre/fsw/portfolios/nvr/projects/nvr_torontoai_humanmotionfm/workspaces/motiondiff/motiondiff_results/jiefengl/gvhmr
ckpt_path: null

use_wandb: true
rsync_ckpt: true


# ================================ #
#          global setting          #
# ================================ #

video_name: ???
output_root: outputs/demo
output_dir: "${output_root}/${text1_video_name}"
preprocess_dir: ${output_dir}/preprocess
video_path: "${output_dir}/0_input_video.mp4"

# Options
text1: null
text1_file: null
text1_video_path: null
text1_video_name: null
text_length: 300
static_cam: False
verbose: False

paths:
  bbx: ${preprocess_dir}/bbx.pt
  bbx_xyxy_video_overlay: ${preprocess_dir}/bbx_xyxy_video_overlay.mp4
  vit_features: ${preprocess_dir}/vit_features.pt
  vimo_pred: ${preprocess_dir}/vimo_pred.pt
  vitpose: ${preprocess_dir}/vitpose.pt
  vitpose_video_overlay: ${preprocess_dir}/vitpose_video_overlay.mp4
  hmr4d_results: ${output_dir}/hmr4d_results.pt
  incam_video: ${output_dir}/1_incam.mp4
  global_video: ${output_dir}/2_global.mp4
  incam_global_horiz_video: ${output_dir}/3_incam_global_horiz.mp4
  slam: ${preprocess_dir}/camera.npy
