humanml3d_eval:
  _target_: genmo.datasets.pure_motion.humanml3d.Humanml3dDataset
  eval_gen_only: true
  cam_augmentation: v11
  use_random_subset: true
  random_subset_size: 2
  random_subset_seed: 7
