python tools/test_slurm.py -u jinkunc -cmd "python tools/train_v2.py trial_ind=1 global/task=mv2d/save_text2motion_feats_motionx exp=unimfm/unimfm_est_st_norm_di_lg_mx3_cp1  exp_name_var=g8 +test_checkpoint=s050000 ++pipeline.args.test_motion_len=196 text_feats_dir=text_feats_196 logger.entity=nv-welcome"
python tools/test_slurm.py -u jinkunc -cmd "python tools/train_v2.py trial_ind=1 global/task=mv2d/save_text2motion_feats_motionx exp=unimfm/unimfm_est_st_norm_di_lg_mx3_cp2  exp_name_var=g8 +test_checkpoint=s050000 ++pipeline.args.test_motion_len=196 text_feats_dir=text_feats_196 logger.entity=nv-welcome"
python tools/test_slurm.py -u jinkunc -cmd "python tools/train_v2.py trial_ind=1 global/task=mv2d/save_text2motion_feats_motionx exp=unimfm/unimfm_est_st_norm_di_lg_mx3_cp3  exp_name_var=g8 +test_checkpoint=s050000 ++pipeline.args.test_motion_len=196 text_feats_dir=text_feats_196 logger.entity=nv-welcome"
python tools/test_slurm.py -u jinkunc -cmd "python tools/train_v2.py trial_ind=1 global/task=mv2d/save_text2motion_feats_motionx exp=unimfm/unimfm_est_st_norm_di_lg_mx3_cp4  exp_name_var=g8 +test_checkpoint=s050000 ++pipeline.args.test_motion_len=196 text_feats_dir=text_feats_196 logger.entity=nv-welcome"

python tools/test_slurm.py -u jinkunc -cmd "python tools/train_v2.py trial_ind=2 global/task=mv2d/save_text2motion_feats_motionx exp=unimfm/unimfm_est_st_norm_di_lg_mx3_cp1  exp_name_var=g8 +test_checkpoint=s050000 ++pipeline.args.test_motion_len=196 text_feats_dir=text_feats_196 logger.entity=nv-welcome"
python tools/test_slurm.py -u jinkunc -cmd "python tools/train_v2.py trial_ind=2 global/task=mv2d/save_text2motion_feats_motionx exp=unimfm/unimfm_est_st_norm_di_lg_mx3_cp2  exp_name_var=g8 +test_checkpoint=s050000 ++pipeline.args.test_motion_len=196 text_feats_dir=text_feats_196 logger.entity=nv-welcome"
python tools/test_slurm.py -u jinkunc -cmd "python tools/train_v2.py trial_ind=2 global/task=mv2d/save_text2motion_feats_motionx exp=unimfm/unimfm_est_st_norm_di_lg_mx3_cp3  exp_name_var=g8 +test_checkpoint=s050000 ++pipeline.args.test_motion_len=196 text_feats_dir=text_feats_196 logger.entity=nv-welcome"
python tools/test_slurm.py -u jinkunc -cmd "python tools/train_v2.py trial_ind=2 global/task=mv2d/save_text2motion_feats_motionx exp=unimfm/unimfm_est_st_norm_di_lg_mx3_cp4  exp_name_var=g8 +test_checkpoint=s050000 ++pipeline.args.test_motion_len=196 text_feats_dir=text_feats_196 logger.entity=nv-welcome"

python tools/test_slurm.py -u jinkunc -cmd "python tools/train_v2.py trial_ind=3 global/task=mv2d/save_text2motion_feats_motionx exp=unimfm/unimfm_est_st_norm_di_lg_mx3_cp1  exp_name_var=g8 +test_checkpoint=s050000 ++pipeline.args.test_motion_len=196 text_feats_dir=text_feats_196 logger.entity=nv-welcome"
python tools/test_slurm.py -u jinkunc -cmd "python tools/train_v2.py trial_ind=3 global/task=mv2d/save_text2motion_feats_motionx exp=unimfm/unimfm_est_st_norm_di_lg_mx3_cp2  exp_name_var=g8 +test_checkpoint=s050000 ++pipeline.args.test_motion_len=196 text_feats_dir=text_feats_196 logger.entity=nv-welcome"
python tools/test_slurm.py -u jinkunc -cmd "python tools/train_v2.py trial_ind=3 global/task=mv2d/save_text2motion_feats_motionx exp=unimfm/unimfm_est_st_norm_di_lg_mx3_cp3  exp_name_var=g8 +test_checkpoint=s050000 ++pipeline.args.test_motion_len=196 text_feats_dir=text_feats_196 logger.entity=nv-welcome"
python tools/test_slurm.py -u jinkunc -cmd "python tools/train_v2.py trial_ind=3 global/task=mv2d/save_text2motion_feats_motionx exp=unimfm/unimfm_est_st_norm_di_lg_mx3_cp4  exp_name_var=g8 +test_checkpoint=s050000 ++pipeline.args.test_motion_len=196 text_feats_dir=text_feats_196 logger.entity=nv-welcome"

python tools/test_slurm.py -u jinkunc -cmd "python tools/train_v2.py trial_ind=4 global/task=mv2d/save_text2motion_feats_motionx exp=unimfm/unimfm_est_st_norm_di_lg_mx3_cp1  exp_name_var=g8 +test_checkpoint=s050000 ++pipeline.args.test_motion_len=196 text_feats_dir=text_feats_196 logger.entity=nv-welcome"
python tools/test_slurm.py -u jinkunc -cmd "python tools/train_v2.py trial_ind=4 global/task=mv2d/save_text2motion_feats_motionx exp=unimfm/unimfm_est_st_norm_di_lg_mx3_cp2  exp_name_var=g8 +test_checkpoint=s050000 ++pipeline.args.test_motion_len=196 text_feats_dir=text_feats_196 logger.entity=nv-welcome"
python tools/test_slurm.py -u jinkunc -cmd "python tools/train_v2.py trial_ind=4 global/task=mv2d/save_text2motion_feats_motionx exp=unimfm/unimfm_est_st_norm_di_lg_mx3_cp3  exp_name_var=g8 +test_checkpoint=s050000 ++pipeline.args.test_motion_len=196 text_feats_dir=text_feats_196 logger.entity=nv-welcome"
python tools/test_slurm.py -u jinkunc -cmd "python tools/train_v2.py trial_ind=4 global/task=mv2d/save_text2motion_feats_motionx exp=unimfm/unimfm_est_st_norm_di_lg_mx3_cp4  exp_name_var=g8 +test_checkpoint=s050000 ++pipeline.args.test_motion_len=196 text_feats_dir=text_feats_196 logger.entity=nv-welcome"

